name: dbt FF Tests

# **What it does**: Runs our tests.
# **Why we have it**: We want our tests to pass before merging code.
# **Who does it impact**: Contributors and maintainers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        dbt-version: ["1.0", "1.1", "1.2", "1.3"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dbt ${{ matrix.dbt-version }}
        if: ${{ matrix.dbt-version != "1.0" }}
        run: pip install . dbt-core==${{ matrix.dbt-version }} pytest
      - name: Install dbt ${{ matrix.dbt-version }} (with Markupsafe pin)
        if: ${{ matrix.dbt-version == "1.0" }}
        run: pip install . dbt-core==${{ matrix.dbt-version }} pytest markupsafe==2.0.1
      - name: Run Tests
        run: pytest
